config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :goals
  get "/goals/:id/complete",to: "goals#complete" ,as: "complete_goal"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :user

  def self.categories
    ['health', 'diet', 'beauty', 'education', 'career', 'social', 'spiritual', 'eco', 'recreation', 'financial', ' general goal ']
  end

  # validations
  validates :title, presence: true
  validates :category, presence: true, inclusion: { in: categories }

  has_one_attached :photo

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :goals, dependent: :destroy
  has_one_attached :photo

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  # Pundit: allow-list approach
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

end

app/controllers/goals_controller.rb
require 'open-uri'

class GoalsController < ApplicationController
  before_action :set_goal, only: [:complete, :edit, :update, :destroy]

  def index
    # @user_goals = Goal.where(user: current_user) if current_user != admin
    # @goals = policy_scope(Goal).order(:completed, :created_at)
    @goals = policy_scope(Goal).where(user: current_user)
    @completed_goals = @goals.where(completed: true)
    @ongoing_goals = @goals.where(completed: false)
    # raise

  end

  def new
    @goal = Goal.new
    authorize @goal
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user = current_user
    unless @goal.photo.attached?
      attach_random_photo(@goal)
    end
    if @goal.save
      redirect_to goals_path
      authorize @goal
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def complete
    @goal.completed = !@goal.completed
    @goal.save
    redirect_to goals_path
  end

  def update
    @goal.update(goal_params)
    @goal.save
    redirect_to goals_path
  end

  def destroy
    @goal.destroy
    redirect_to goals_path
  end

  private

  def set_goal
    @goal = Goal.find(params[:id])
    authorize @goal
  end

  def goal_params
    params.require(:goal).permit(:category, :title, :description, :photo )
  end

  def attach_random_photo(goal)
    photo_url = "https://source.unsplash.com/random/240x120/?#{goal.category}"
    file = URI.open(photo_url)
    goal.photo.attach(io: file, filename: 'default.png', content_type: 'image/png')
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/_card-completed.html.erb
<div class="cards">

        <% if goals.size > 0 %>
          <% goals.each do |goal| %>

            <div class="card-custom h-100 text-center border border-5 border-primary" style="width: 18rem; border-radius: 2.0rem;">
            <%= image_tag "#{goal.photo.attached? ? cl_image_path(goal.photo.key) : "" }", class:"card-img-custom mb-2", alt:"..."%>
                <div class="card-body">
                  <div class="card-title mb-3 p-2 fs-4"><%= goal.title %></div>
                      <div class="card-edit-menu">
                        <%= link_to edit_goal_path(goal) do %>
                          <p class="card-text"><i class="fa-regular fa-pen-to-square"></i> Edit</p>
                        <% end %>
                          <%= link_to complete_goal_path(goal) do %>
                            <p class="card-text"><i class="fa-solid fa-arrow-rotate-left"></i> Ongoing</p>
                          <% end %>
                            <%= link_to goal_path(goal), data: { turbo_method: :delete, turbo_confirm: "Delete #{goal.title}?" } do %>
                              <p><i class="fa-regular fa-trash-can"></i> Delete</p>
                            <% end %>
                      </div>
                    <p>
                      <a class="btn btn-warning" data-bs-toggle="collapse" href="#collapseBody" role="button" aria-expanded="false" aria-controls="collapseBody">
                        About...
                      </a>
                    </p>
                      <div class="collapse" id="collapseBody">
                        <div class="p-2">
                          <p class="card-text"> <i class="fa-solid fa-quote-left"></i> <%= goal.category %> <i class="fa-solid fa-quote-right"></i></p>
                          <p class="card-text"><i class="fa-regular fa-comment-dots"></i> <%= goal.description.blank? ? "you can add a description through the pencil mark!" : goal.description %></p>
                        </div>
                      </div>
                    </div>
                    </div>



          <% end %>
        <% else %>
          <h2>No goals here yet!</h2>
        <% end %>
</div>

app/views/goals/_card.html.erb
<div class="cards">

        <% if goals.size > 0 %>
          <% goals.each do |goal| %>

            <div class="card-custom h-100 text-center border border-5 border-warning" style="width: 18rem; border-radius: 2.0rem;">
            <%= image_tag "#{goal.photo.attached? ? cl_image_path(goal.photo.key) : "" }", class:"card-img-custom mb-2", alt:"..."%>
              <div class="card-body">
                <div class="card-bottom">
                  <div class="card-title mb-3 p-2 fs-4"><%= goal.title %></div>
                      <div class="card-edit-menu">
                        <%= link_to edit_goal_path(goal) do %>
                          <p class="card-text"><i class="fa-regular fa-pen-to-square"></i> Edit</p>
                        <% end %>
                          <%= link_to complete_goal_path(goal) do %>
                            <p class="card-text"><i class="fa-solid fa-circle-check"></i> Reached!</p>
                          <% end %>
                            <%= link_to goal_path(goal), data: { turbo_method: :delete, turbo_confirm: "Delete #{goal.title}?" } do %>
                              <p><i class="fa-regular fa-trash-can"></i> Delete</p>
                            <% end %>
                      </div>
                    <p>
                      <a class="btn btn-warning" data-bs-toggle="collapse" href="#collapseBody" role="button" aria-expanded="false" aria-controls="collapseBody">
                        About...
                      </a>
                    </p>
                      <div class="collapse" id="collapseBody">
                        <div class="p-2">
                          <p class="card-text"> <i class="fa-solid fa-quote-left"></i> <%= goal.category %> <i class="fa-solid fa-quote-right"></i></p>
                          <p class="card-text"><i class="fa-regular fa-comment-dots"></i> <%= goal.description.blank? ? "you can add a description through the pencil mark!" : goal.description %></p>
                        </div>
                      </div>
                    </div>
                </div>
                    </div>
          <% end %>
        <% else %>
          <h2>No goals here yet!</h2>
        <% end %>
</div>

app/views/goals/_form.html.erb
<%= simple_form_for(goal) do |f| %>
  <%= f.input :title, label: 'Goal title', placeholder:"Give your goal a title here", autofocus: true %>
  <%= f.input :category, :collection => Goal.categories %>
  <%= f.input :description , placeholder:"You can describe your goal here"  %>

  <%= f.input :photo, as: :file %>
  <%= f.submit "Go!", class: 'btn btn-primary mt-2 opacity-75' %>
<% end %>

app/views/goals/_table.html.erb
<p>
  <a class="btn btn-warning" data-bs-toggle="collapse" href="#collapseTracker" role="button" aria-expanded="false" aria-controls="collapseTracker">
    Track <i class="fa-solid fa-list-check"></i>
  </a>
</p>
  <div class="collapse" id="collapseTracker">
    <div style="min-width:240px;">
      <ul class="list-group" , style="border-radius: 2rem;">
<li class="list-group-item list-group-item-primary""> Goals Reached / Total (%)</li>
  <% goals.pluck(:category).uniq.each do |cat| %>
  <li class="list-group-item">
    <%= cat %>:
      <%= completed_goals.where(category: cat).size %> / <%= goals.where(category: cat).size %> (<%= (completed_goals.where(category: cat).size.to_f  /  goals.where(category: cat).size.to_f * 100).to_i %> %)
  </li>
  <% end %>
</ul>
 </div>
  </div>

app/views/goals/edit.html.erb
<div class="back-img">
<div class="container mt-4 p-4">
<div class="form-centered mt-4 p-4">
  <h1><%= "Edit '#{@goal.title}'" %> </h1>
    <div class="mt-3" style="width: 18rem;">
      <%= render "form", goal: @goal %>
    </div>
</div>
</div>
</div>

app/views/goals/index.html.erb
<div class="back-img">
<div class="container p-5 mt-3" style ="background-color:rgba(255, 255, 255, 0.8);">
  <div class="fs-4 mb-3"> Ready to reach a new peak?
      <div class="btn btn-warning" >
        <%= link_to new_goal_path, style:"text-decoration:none;" do %>
      Add <i class="fa-solid fa-plus"></i>
    <% end %>
    </div>
  </div>
  <div class="goals_tracker-parent">
    <div class="goals-ongoing mb-3">
      <div class="title mb-3"> <i class="fa-solid fa-person-walking"></i> Ongoing: </div>
        <%= render 'goals/card', goals: @ongoing_goals %>
    </div>
    <div class="goals-completed mb-3">
          <div class="title mb-3"><i class="fa-solid fa-font-awesome"></i> Reached: </div>
            <%= render 'goals/card-completed', goals: @completed_goals %>
    </div>
    <div class="goals-progress">

  <%= render 'goals/table', goals: @goals, completed_goals: @completed_goals %>
  </div>
</div>
</div>
</div>

app/views/goals/new.html.erb
<div class="back-img">
<div class="container mt-4 p-4">
<div class="form-centered mt-4 p-4">
  <h1>Add a goal </h1>
    <div class="mt-3" style="width: 18rem;">
      <%= render "form", goal: @goal %>
    </div>
    </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Think-Peaks:Your goal tracker</title>
    <%= favicon_link_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="back-img">
<div class="banner">
  <div class="container">
    <% if user_signed_in? %>
    <h1>Welcome back to Think-Peaks, <%= current_user.email.split("@")[0].capitalize %></h1>
      <p>Ready to track your goals?
        <%= link_to goals_path do %>
          <button type="button" class="btn btn-warning">Let's Go!</button>
        <% end %>
    <% else %>
    <h1>Welcome to Think-Peaks</h1>
      <p> We help you set and track your goals.
        <%= link_to new_user_session_path do %>
          <button type="button" class="btn btn-warning">Log in</button>
        <% end %>
    <% end %>

</div>
        <p class="banner-attribution">Photo by Jeremy Bishop on Unsplash</p>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-goaltrk">
  <div class="container-fluid">
    <%= link_to "/", class: "navbar-brand" do %>
      Think-Peaks
      <i class="fa-brands fa-think-peaks"></i>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <div class="navbar-menu">
            <%= link_to  new_goal_path, class: "nav-link"  do %>
              <i class="fa-solid fa-plus"></i> Add a goal
            <% end %>

              <%= link_to goals_path, class: "nav-link" do %>
              <i class="fa-solid fa-chart-gantt"></i> Track your goals
              <% end %>

              <%= link_to destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" do %>
              <i class="fa-solid fa-right-from-bracket"></i> Log out
              <% end %>

          </div>
          </li>
          <li class="nav-item dropdown">
          <%# <%= image_tag "#{current_user.photo.attached? ? cl_image_path(current_user.photo.key) : "" }", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown" >
              <%= link_to "Add a new goal", new_goal_path, class: "dropdown-item" %>
              <%= link_to "Track your goals", goals_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <div class="navbar-menu">
          <%= link_to new_user_session_path, class: "nav-link" do %>
              Log in
            <% end %>

        </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>